### ISSUE TITLE
[STORY]: Store Subrecipient Data

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/cpf-reporter#291]
### Full User Story

This issue will be a dependency for the following user stories:
- As a partner admin, I want to be able to generate a treasury report that includes a subrecipient file of only new subrecipients. 
- As an agency reporter, I want to be able to receive upload validation errors if I do not include both UEI and TIN for new subrecipients only. 

### Why is this issue important?

To be able to generate the treasury file correctly, we need to know which subrecipients are new (i.e. subrecipients with the same UEI or TIN numbers have not been sent to Treasury previously for CPF reports from the partner)

### Action Plan
- [ ] Initial acceptance criteria drafted
- [ ] High level technical approach & feature flag use determined
- [ ] Acceptance criteria finalized
- [ ] Eng task breakout complete
- [ ] Assessment of whether partner training & communication actions are needed
- [ ] Acceptance criteria testing completed & passed in staging

### Engineering Tasks

Add links to engineering tasks

### Acceptance Criteria
- Every time a file is uploaded or revalidated and passes validation, any new subrecipients in that report are stored 
- A subrecipient is considered "new" if there is no matching UEI or TIN in previous closed reporting periods for that agency and EC code
- After the first reporting period a subrecipient exists in is closed, they will be considered as "existing" records and will not be considered "new"
- if an upload is invalidated and has new subrecipients in it (i.e. they were first reported in that reporting period), those records will be removed. If they are added again in that reporting period or a future one, they will be considered "new" again
- if a subrecipient is new during the current reporting period, but then another valid file is submitted for the current reporting period, agency, and program, and has a subrecipient with matching UEI or TIN, the subrecipient record will be replaced with the most recent valid file
- The following fields should be stored for each subrecipient: TBD!!! (i believe we will need project id, agency id, ec code, reporting period added)
- Note - this issue does NOT include any functionality for the treasury report or upload validation - this will be in separate issues

**Comment by ClaireValdivia** [comment]
**closing this issue as this logic is already addressed in subrecipient file work for treasury report
