### ISSUE TITLE
USER STORY: Login Flow

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#78]
### Full User Story
As a user, I want to login into the CPF Reporter tool, so I can access the tool that reduces my workload.

### Action Plan

- [x] Initial design drafted
- [x] Initial acceptance criteria drafted
- [ ] High level technical approach & feature flag use determined
- [ ] Designs & Acceptance criteria finalized
- [ ] Eng task breakout complete
- [ ] Assessment of whether partner training & communication actions are needed
- [ ] Acceptance criteria testing completed & passed in staging
- [ ] Feature flags enabled in production

### Engineering Tasks

- [Login flow](https://github.com/orgs/usdigitalresponse/projects/5/views/34?pane=issue&itemId=43760251)

### Acceptance Criteria

- When a user gets to the tool main address, they are prompted to enter their email address to recieve a log in link. When they click the "send email with login link" button, if the email address is not associated with a user, a red box that reads "User '[email]' not found" pops up below the "send email with login link" button. If the email address is associated with a user in the system, an email is sent to the entered email address and a green box that reads "Email sent to [email]. Check your inbox." pops up. The email contains the text: "Your link to access USDR's Grants Tool is [link]. It expires in 30 minutes". When the user opens the link, it brings them to the CPF tool uploads page, logged into their account.
