### ISSUE TITLE
USER STORY: User Management

### ISSUE THREAD

**Issue by snyde664** [usdigitalresponse/cpf-reporter#81]
### Full User Story
As an admin user, I want to create and manage users, so that they can work through the workbook upload process and I can keep their uploads organized. 

### Action Plan

- [ ] Initial design drafted
- [ ] Initial acceptance criteria drafted
- [ ] High level technical approach & feature flag use determined
- [ ] Designs & Acceptance criteria finalized
- [ ] Eng task breakout complete
- [ ] Assessment of whether partner training & communication actions are needed
- [ ] Acceptance criteria testing completed & passed in staging
- [ ] Feature flags enabled in production

### Engineering Tasks

- [User Management: Users page / Viewing Users functionality](https://github.com/orgs/usdigitalresponse/projects/5/views/34?filterQuery=label%3A%22cpf+quarterly+reporter%22+user&pane=issue&itemId=44762614)
- [User Management: Adding Users functionality](https://github.com/orgs/usdigitalresponse/projects/5/views/34?filterQuery=label%3A%22cpf+quarterly+reporter%22+user&pane=issue&itemId=44763683)
- [User Management: Editing Users functionality](https://github.com/orgs/usdigitalresponse/projects/5/views/34?filterQuery=label%3A%22cpf+quarterly+reporter%22+user&pane=issue&itemId=44764610)
- [ ] #84 

#### Users Page / Viewing Users

- When a user clicks on the Users tab, they are sent to the Users page:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/6d93129a-059f-4d13-93bb-ebc3eb318419)

This page should include:

- page title of “Users”
- “Create New User” Button
- Table of existing users with:
  - Search capability
  - Columns:
    - Email
    - Name
    - Role: Staff or Admin
    - Agency
    - Created: Creation time / date
    - Edit: Edit button for individual user  

#### Adding Users
 Clicking on the “Create New User” button should lead to the Create New User page:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/55fecdb2-4485-4cd5-94c2-81e1130548de)

This page should include the following:

- Page title of “User”
- Frozen ID textbox
- Email textbox
- Name textbox
- Role dropdown with the options: Organization Admin, Organization Staff, and USDR Admin (this should only be an option if the user creating the new user is a USDR Admin User)
- Agency dropdown with existing agencies in the tenant as options
- Reset button: clears all entered information
- Save button: adds a user based on entered information
  - Email, name, role, and agency are required fields. If any of these is missing, an error message will appear under the missing field textboxes and the user will not be saved.

Saving a user adds them to the database, and therefore the table, of users and creates a user account for them. This allows the user to login with their associated email.

#### Editing Users
Clicking on the “Edit” button in a row of the User table should lead to the selected User’s page. This is the same page as the Create New User page, but all of the User’s existing information will be displayed:

![Image](https://github.com/usdigitalresponse/cpf-reporter/assets/44246589/ecfe0961-8283-4ff0-abd9-d86e01c5e598)

Here, the user should be able to edit all the information beside the ID number, and click the Save button to save their changes. These changes should be reflected in the table of users.
